theme: jekyll-theme-tactile
title: SANS SEC505
description: PowerShell scripts, templates and other files supporting the six-day Securing Windows and PowerShell Automation course at the SANS Institute.
