theme: jekyll-theme-tactile
title: SANS SEC505 Securing Windows and PowerShell Automation
description: PowerShell scripts, templates and other files supporting the six-day Securing Windows and PowerShell Automation course at the SANS Institute (https://sans.org/sec505).
